/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/K7Lm5ql
 */
import Link from "next/link";
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  CardFooter,
  Card,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import {
  SelectValue,
  SelectTrigger,
  SelectLabel,
  SelectItem,
  SelectGroup,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";

export function ProductEditForm() {
  return (
    <div className="flex flex-col">
      <div className="mt-10 mb-10">
        <Card className="max-w-2xl mx-auto">
          <CardHeader>
            <CardTitle>Add or Update Product</CardTitle>
            <CardDescription>
              Add or update a product in your catalog.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="space-y-2">
                <Label htmlFor="product-name">Product name</Label>
                <Input id="product-name" placeholder="Acme Prism T-Shirt" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="price">Price</Label>
                <Input id="price" placeholder="99.99" type="number" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="color">Color</Label>
                  <Input id="color" placeholder="Black" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="size">Size</Label>
                  <Input id="size" placeholder="M" />
                </div>
              </div>
              <div className="space-y-2">
                <Label htmlFor="description">Description</Label>
                <Input
                  id="description"
                  placeholder="60% combed ringspun cotton/40% polyester jersey tee."
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="image">Image</Label>
                <Input id="image" placeholder="/path/to/image.jpg" />
              </div>
              <div className="space-y-2">
                <Label htmlFor="role">Role</Label>
                <Select required>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a role" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectGroup>
                      <SelectLabel>Roles</SelectLabel>
                      <SelectItem value="admin">Admin</SelectItem>
                      <SelectItem value="user">User</SelectItem>
                    </SelectGroup>
                  </SelectContent>
                </Select>
              </div>
            </div>
          </CardContent>
          <CardFooter>
            <Button className="w-full" type="submit">
              Create User
            </Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  );
}
